### ISSUE TITLE
Installation instructions/dependencies

### ISSUE THREAD

**Issue by wdecoster** [Transipedia/dekupl#3]
Could you please add installation instructions and a list of dependencies?
In addition, making this available through (bio)conda would be great.

I naively cloned the repo and ran `make`:
```
jekyll build
make: jekyll: Command not found
make: *** [build] Error 127
```

Looks like I (at least) miss jekyll.

**Comment by rchikhi** [comment]
Thanks for your feedback.
This is indeed misleading and you're not supposed to checkout this `dekupl` repo, the main software is at https://github.com/Transipedia/dekupl-run and https://github.com/Transipedia/dekupl-annotation. 
We should make the README more clear. 
Also @jaudoux, what do you think about moving the website to a `website` branch on that repo?

**Comment by jaudoux** [comment]
@rchikhi yes I think it is a good idea, I'll try to do that asap.

**Comment by rchikhi** [comment]
done

**Comment by pkr2103** [comment]
Thanks so much for making what seems like an awesome tool.  I want to use it! But I have a basic problem.  I can't install it from conda on a macintosh. 
 
I tried to install dekupl-run etc via conda and I keep getting this odd error:
 
conda install -n dekupl -y -m --override-channels -c transipedia -c bioconda -c conda-forge -c https://repo.anaconda.com/pkgs/main -c https://repo.anaconda.com/pkgs/free -c https://repo.anaconda.com/pkgs/pro -c r dekupl-run  dekupl-annotation dekupl-viewer
Solving environment: failed
 
PackagesNotFoundError: The following packages are not available from current channels:
 
  - dekupl-run
  - libgcc-ng[version='>=7.3.0']
  - dekupl-annotation
 
Current channels:
 
  - https://conda.anaconda.org/Transipedia/osx-64
  - https://conda.anaconda.org/Transipedia/noarch
  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/pro/osx-64
  - https://repo.anaconda.com/pkgs/pro/noarch
  - https://conda.anaconda.org/r/osx-64
  - https://conda.anaconda.org/r/noarch
 
Is there something simple I am missing? It seems like dekupl-run is not available on your conda channel for some reason.
 
Thanks so much!

**Comment by dgautheret** [comment]
Salut Rayan,

Tu vois quoi lui dire ou on demande à SeqOne? 

Amicalement,
D.

> Le 8 mai 2019 à 16:37, Kirk <notifications@github.com> a écrit :
> 
> Thanks so much for making what seems like an awesome tool. I want to use it! But I have a basic problem. I can't install it from conda on a macintosh.
> 
> I tried to install dekupl-run etc via conda and I keep getting this odd error:
> 
> conda install -n dekupl -y -m --override-channels -c transipedia -c bioconda -c conda-forge -c https://repo.anaconda.com/pkgs/main -c https://repo.anaconda.com/pkgs/free -c https://repo.anaconda.com/pkgs/pro -c r dekupl-run dekupl-annotation dekupl-viewer
> Solving environment: failed
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
> 	• dekupl-run
> 	• libgcc-ng[version='>=7.3.0']
> 	• dekupl-annotation
> Current channels:
> 
> 	• https://conda.anaconda.org/Transipedia/osx-64
> 	• https://conda.anaconda.org/Transipedia/noarch
> 	• https://conda.anaconda.org/bioconda/osx-64
> 	• https://conda.anaconda.org/bioconda/noarch
> 	• https://conda.anaconda.org/conda-forge/osx-64
> 	• https://conda.anaconda.org/conda-forge/noarch
> 	• https://repo.anaconda.com/pkgs/main/osx-64
> 	• https://repo.anaconda.com/pkgs/main/noarch
> 	• https://repo.anaconda.com/pkgs/free/osx-64
> 	• https://repo.anaconda.com/pkgs/free/noarch
> 	• https://repo.anaconda.com/pkgs/pro/osx-64
> 	• https://repo.anaconda.com/pkgs/pro/noarch
> 	• https://conda.anaconda.org/r/osx-64
> 	• https://conda.anaconda.org/r/noarch
> Is there something simple I am missing? It seems like dekupl-run is not available on your conda channel for some reason.
> 
> Thanks so much!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


-- 
Daniel Gautheret   
Institute for Integrative Biology of the Cell
UMR 9198 - Universite Paris-Sud
Bat 400 - 91405 Orsay cedex 
Tel Direct: 33 (0)1 69 82 62 38
http://rna.igmors.u-psud.fr

**Comment by rchikhi** [comment]
Hello Daniel,

Unfortunately I'm not running OSX so I cannot help here. @jaudoux is dekupl supposed to work with conda in OSX? Otherwise, @pkr2103 you could use Options 2 or 3 from https://github.com/Transipedia/dekupl-run
